import WidgetKit
import SwiftUI
import SwiftData
import AppIntents
private let appGroupIdentifier = "group.com.youmind.islandlink"
@MainActor func widgetModelContainer() -> ModelContainer { let sharedDirectory = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: appGroupIdentifier)!; let storeURL = sharedDirectory.appendingPathComponent("IslandLink.sqlite"); let config = ModelConfiguration(url: storeURL); do { return try ModelContainer(for: Person.self, Case.self, Event.self, CaseEvent.self, Tag.self, CasePerson.self, EventPerson.self, EventCase.self, configurations: config) } catch { fatalError("Widget ModelContainer 初始化失败: \(error)") } }
@MainActor struct WidgetDataProvider { private let container: ModelContainer; private let context: ModelContext; private let calendar = Calendar.current
    init() { container = widgetModelContainer(); context = container.mainContext }
    func todayEventCount() -> Int { let today = calendar.startOfDay(for: Date()); let tomorrow = calendar.date(byAdding: .day, value: 1, to: today)!; let descriptor = FetchDescriptor<event>(predicate: #Predicate { event in (event.statusRaw == "planned" || event.statusRaw == "confirmed") && (event.date != nil) && (event.date! >= today && event.date! < tomorrow) }); return (try? context.fetchCount(descriptor)) ?? 0 }
    func tomorrowHearingCount() -> Int { let today = calendar.startOfDay(for: Date()); let dayAfterTomorrow = calendar.date(byAdding: .day, value: 2, to: today)!; let tomorrow = calendar.date(byAdding: .day, value: 1, to: today)!; let descriptor = FetchDescriptor<event>(predicate: #Predicate { event in (event.statusRaw == "planned" || event.statusRaw == "confirmed") && (event.date != nil) && (event.date! >= tomorrow && event.date! < dayAfterTomorrow) && (event.eventTypeRaw == "hearing" || event.eventTypeRaw == "开庭") }); return (try? context.fetchCount(descriptor)) ?? 0 }
    func tomorrowEventCount() -> Int { let today = calendar.startOfDay(for: Date()); let dayAfterTomorrow = calendar.date(byAdding: .day, value: 2, to: today)!; let tomorrow = calendar.date(byAdding: .day, value: 1, to: today)!; let descriptor = FetchDescriptor<event>(predicate: #Predicate { event in (event.statusRaw == "planned" || event.statusRaw == "confirmed") && (event.date != nil) && (event.date! >= tomorrow && event.date! < dayAfterTomorrow) }); return (try? context.fetchCount(descriptor)) ?? 0 }
    func activeCaseCount() -> Int { let descriptor = FetchDescriptor<case>(predicate: #Predicate { c in !c.isArchived && (c.caseStatusRaw == "consulting" || c.caseStatusRaw == "retained" || c.caseStatusRaw == "filing" || c.caseStatusRaw == "inTrial" || c.caseStatusRaw == "enforcing" || c.caseStatusRaw == "appealed") }); return (try? context.fetchCount(descriptor)) ?? 0 }
    func caseStatusDistribution() -> [(status: CaseStatus, count: Int)] { let activeStatuses: [CaseStatus] = [.consulting, .retained, .filing, .inTrial, .enforcing, .appealed]; var result: [(status: CaseStatus, count: Int)] = []; for status in activeStatuses { let descriptor = FetchDescriptor<case>(predicate: #Predicate { c in !c.isArchived && c.caseStatusRaw == status.rawValue }); let count = (try? context.fetchCount(descriptor)) ?? 0; if count > 0 { result.append((status, count)) } }; return result }
    func nextHearing() -> (title: String, date: Date)? { let now = Date(); let eventDescriptor = FetchDescriptor<event>(predicate: #Predicate { event in (event.statusRaw == "planned" || event.statusRaw == "confirmed") && (event.date != nil) && (event.date! >= now) && (event.eventTypeRaw == "hearing") }, sortBy: [SortDescriptor(\.date, order: .forward)]); let upcomingHearings = (try? context.fetch(eventDescriptor)) ?? []; let caseEventDescriptor = FetchDescriptor<caseevent>(predicate: #Predicate { ce in !ce.isCompleted && ce.date >= now && (ce.eventTypeRaw == "trial" || ce.eventTypeRaw == "sentencing") }, sortBy: [SortDescriptor(\.date, order: .forward)]); let upcomingCaseEvents = (try? context.fetch(caseEventDescriptor)) ?? []; if let firstEvent = upcomingHearings.first, let firstCaseEvent = upcomingCaseEvents.first { if firstEvent.date! < firstCaseEvent.date { return (firstEvent.title, firstEvent.date!) } else { return (firstCaseEvent.title, firstCaseEvent.date) } }; if let firstEvent = upcomingHearings.first, let date = firstEvent.date { return (firstEvent.title, date) }; if let firstCaseEvent = upcomingCaseEvents.first { return (firstCaseEvent.title, firstCaseEvent.date) }; return nil }
    func thisWeekEventCount() -> Int { let now = Date(); let weekday = calendar.component(.weekday, from: now); let daysToMonday = (weekday + 5) % 7; let monday = calendar.startOfDay(for: calendar.date(byAdding: .day, value: -daysToMonday, to: now)!); let nextMonday = calendar.date(byAdding: .day, value: 7, to: monday)!; let descriptor = FetchDescriptor<event>(predicate: #Predicate { event in event.date != nil && event.date! >= monday && event.date! < nextMonday }); return (try? context.fetchCount(descriptor)) ?? 0 }
    func thisWeekHearingCount() -> Int { let now = Date(); let weekday = calendar.component(.weekday, from: now); let daysToMonday = (weekday + 5) % 7; let monday = calendar.startOfDay(for: calendar.date(byAdding: .day, value: -daysToMonday, to: now)!); let nextMonday = calendar.date(byAdding: .day, value: 7, to: monday)!; let descriptor = FetchDescriptor<event>(predicate: #Predicate { event in event.date != nil && event.date! >= monday && event.date! < nextMonday && (event.eventTypeRaw == "hearing" || event.eventTypeRaw == "开庭") }); return (try? context.fetchCount(descriptor)) ?? 0 }
    func thisMonthEventCount() -> Int { let now = Date(); let startOfMonth = calendar.date(from: calendar.dateComponents([.year, .month], from: now))!; let startOfNextMonth = calendar.date(byAdding: .month, value: 1, to: startOfMonth)!; let descriptor = FetchDescriptor<event>(predicate: #Predicate { event in event.date != nil && event.date! >= startOfMonth && event.date! < startOfNextMonth }); return (try? context.fetchCount(descriptor)) ?? 0 }
}
struct WidgetEntry: TimelineEntry { let date: Date; let todayEventCount: Int; let tomorrowEventCount: Int; let tomorrowHearingCount: Int; let activeCaseCount: Int; let caseStatusDistribution: [(status: CaseStatus, count: Int)]; let nextHearing: (title: String, date: Date)?; let thisWeekEventCount: Int; let thisWeekHearingCount: Int; let thisMonthEventCount: Int }
struct IslandLinkProvider: @preconcurrency TimelineProvider { typealias Entry = WidgetEntry
    func placeholder(in context: Context) -> WidgetEntry { WidgetEntry(date: Date(), todayEventCount: 3, tomorrowEventCount: 2, tomorrowHearingCount: 1, activeCaseCount: 5, caseStatusDistribution: [(.inTrial, 2), (.filing, 1), (.consulting, 1), (.retained, 1)], nextHearing: ("张某劳动争议案开庭", Calendar.current.date(byAdding: .day, value: 2, to: Date())!), thisWeekEventCount: 8, thisWeekHearingCount: 2, thisMonthEventCount: 25) }
    func getSnapshot(in context: Context, completion: @escaping (WidgetEntry) -> Void) { completion(placeholder(in: context)) }
    func getTimeline(in context: Context, completion: @escaping (Timeline<widgetentry>) -> Void) { Task { @MainActor in let provider = WidgetDataProvider(); let entry = WidgetEntry(date: Date(), todayEventCount: provider.todayEventCount(), tomorrowEventCount: provider.tomorrowEventCount(), tomorrowHearingCount: provider.tomorrowHearingCount(), activeCaseCount: provider.activeCaseCount(), caseStatusDistribution: provider.caseStatusDistribution(), nextHearing: provider.nextHearing(), thisWeekEventCount: provider.thisWeekEventCount(), thisWeekHearingCount: provider.thisWeekHearingCount(), thisMonthEventCount: provider.thisMonthEventCount()); let refreshDate = Calendar.current.date(byAdding: .minute, value: 30, to: Date())!; completion(Timeline(entries: [entry], policy: .after(refreshDate))) } }
}
struct TodayEventsAccessoryWidget: View { var entry: IslandLinkProvider.Entry; var body: some View { VStack(spacing: 2) { Image(systemName: "hammer.fill").font(.system(size: 14, weight: .semibold)).foregroundColor(.coralWarm); Text("\(entry.todayEventCount)").font(.system(size: 24, weight: .bold, design: .rounded)).foregroundColor(.primary); Text("今天").font(.system(size: 8)).foregroundColor(.secondary) } } }
struct TodayEventsInlineWidget: View { var entry: IslandLinkProvider.Entry; var body: some View { if entry.todayEventCount > 0 { Label("今天 \(entry.todayEventCount) 件事项", systemImage: "hammer.fill") } else { Label("今天无事项", systemImage: "checkmark") } } }
struct TodayEventsRectangularWidget: View { var entry: IslandLinkProvider.Entry; var body: some View { HStack(spacing: 12) { VStack(alignment: .leading, spacing: 2) { Text("今天").font(.caption2).foregroundColor(.secondary); Text("\(entry.todayEventCount)").font(.title.bold()).foregroundColor(.coralWarm); Text("事件").font(.caption2).foregroundColor(.secondary) }; Divider(); VStack(alignment: .leading, spacing: 2) { Text("明天").font(.caption2).foregroundColor(.secondary); Text("\(entry.tomorrowHearingCount)").font(.title.bold()).foregroundColor(.tealLink); Text("开庭").font(.caption2).foregroundColor(.secondary) } } } }
struct QuickActionsSmallWidget: View { var entry: IslandLinkProvider.Entry; var body: some View { VStack(spacing: 10) { HStack(spacing: 4) { Image(systemName: "calendar").font(.caption2); Text("\(entry.todayEventCount) 件事").font(.caption.bold()) }.foregroundColor(.coralWarm); HStack(spacing: 16) { Link(destination: URL(string: "islandlink://new-event")!) { VStack(spacing: 4) { Image(systemName: "plus.circle.fill").font(.system(size: 22)).foregroundColor(.tealLink); Text("新事件").font(.system(size: 8)).foregroundColor(.secondary) } }; Link(destination: URL(string: "islandlink://new-person")!) { VStack(spacing: 4) { Image(systemName: "person.badge.plus").font(.system(size: 22)).foregroundColor(.coralWarm); Text("新联系人").font(.system(size: 8)).foregroundColor(.secondary) } }; Link(destination: URL(string: "islandlink://new-case")!) { VStack(spacing: 4) { Image(systemName: "folder.badge.plus").font(.system(size: 22)).foregroundColor(.oceanDeep); Text("新案件").font(.system(size: 8)).foregroundColor(.secondary) } } } }.padding(12) } }
struct CaseOverviewMediumWidget: View { var entry: IslandLinkProvider.Entry; var body: some View { VStack(alignment: .leading, spacing: 10) { HStack { Image(systemName: "folder.fill").foregroundColor(.tealLink).font(.caption); Text("案件概览").font(.caption.bold()).foregroundColor(.primary); Spacer(); Text("\(entry.activeCaseCount) 进行中").font(.caption2).foregroundColor(.secondary) }; if entry.caseStatusDistribution.isEmpty { Spacer(); HStack { Spacer(); VStack(spacing: 4) { Image(systemName: "tray.full").font(.system(size: 18)).foregroundColor(.secondary.opacity(0.5)); Text("暂无进行中案件").font(.caption2).foregroundColor(.secondary) }; Spacer() }; Spacer() } else { GeometryReader { geo in let total = entry.caseStatusDistribution.reduce(0) { $0 + $1.count }; let barWidth = geo.size.width; HStack(spacing: 1) { ForEach(entry.caseStatusDistribution, id: \.status.rawValue) { item in RoundedRectangle(cornerRadius: 1).fill(item.status.dotColor).frame(width: max(4, barWidth * CGFloat(item.count) / CGFloat(max(1, total)))) } } }.frame(height: 4).clipShape(RoundedRectangle(cornerRadius: 2)); HStack(spacing: 12) { ForEach(entry.caseStatusDistribution.prefix(4), id: \.status.rawValue) { item in HStack(spacing: 3) { Circle().fill(item.status.dotColor).frame(width: 5, height: 5); Text("\(item.status.rawValue) \(item.count)").font(.system(size: 9)).foregroundColor(.secondary) } } } }; if let hearing = entry.nextHearing { HStack(spacing: 4) { Image(systemName: "hammer.fill").font(.system(size: 9)).foregroundColor(.coralWarm); Text(hearing.title).font(.caption2).foregroundColor(.primary).lineLimit(1); Spacer(); Text(hearing.date.formatted(.dateTime.month(.abbreviated).day())).font(.caption2).foregroundColor(.secondary) }.padding(.top, 2) } }.padding(14) } }
struct TodayEventsCircularWidget: Widget { let kind = "TodayEventsCircular"; var body: some WidgetConfiguration { StaticConfiguration(kind: kind, provider: IslandLinkProvider()) { entry in TodayEventsAccessoryWidget(entry: entry).containerBackground(.fill.tertiary, for: .widget) }.configurationDisplayName("今日事件").description("显示今天有几个待办事件").supportedFamilies([.accessoryCircular]) } }
struct TodayEventsInlineWidget_: Widget { let kind = "TodayEventsInline"; var body: some WidgetConfiguration { StaticConfiguration(kind: kind, provider: IslandLinkProvider()) { entry in TodayEventsInlineWidget(entry: entry) }.configurationDisplayName("今日摘要").description("在锁屏顶部显示今日事项摘要").supportedFamilies([.accessoryInline]) } }
struct TodayEventsRectangularWidget_: Widget { let kind = "TodayEventsRectangular"; var body: some WidgetConfiguration { StaticConfiguration(kind: kind, provider: IslandLinkProvider()) { entry in TodayEventsRectangularWidget(entry: entry).containerBackground(.fill.tertiary, for: .widget) }.configurationDisplayName("今日/明日").description("对比今天事项和明天开庭数").supportedFamilies([.accessoryRectangular]) } }
struct QuickActionsSmallWidget_: Widget { let kind = "QuickActionsSmall"; var body: some WidgetConfiguration { StaticConfiguration(kind: kind, provider: IslandLinkProvider()) { entry in QuickActionsSmallWidget(entry: entry).containerBackground(.fill.tertiary, for: .widget) }.configurationDisplayName("快捷操作").description("快速新建事件、联系人、案件").supportedFamilies([.systemSmall]) } }
struct CaseOverviewMediumWidget_: Widget { let kind = "CaseOverviewMedium"; var body: some WidgetConfiguration { StaticConfiguration(kind: kind, provider: IslandLinkProvider()) { entry in CaseOverviewMediumWidget(entry: entry).containerBackground(.fill.tertiary, for: .widget) }.configurationDisplayName("案件概览").description("进行中案件数及状态分布").supportedFamilies([.systemMedium]) } }
@main struct IslandLinkWidgetBundle: WidgetBundle { var body: some Widget { TodayEventsCircularWidget(); TodayEventsInlineWidget_(); TodayEventsRectangularWidget_(); QuickActionsSmallWidget_(); CaseOverviewMediumWidget_() } }