import UserNotifications
import SwiftUI
@MainActor final class NotificationManager: ObservableObject { static let shared = NotificationManager(); private let center = UNUserNotificationCenter.current()
    func requestAuthorization() { center.requestAuthorization(options: [.alert, .badge, .sound]) { granted, error in if let error { print("[NotificationManager] 通知权限请求失败: \(error.localizedDescription)") } else if granted { print("[NotificationManager] 通知权限已授权") } else { print("[NotificationManager] 用户拒绝了通知权限") } } }
    func scheduleReminder(for event: Event) { guard event.shouldRemind else { return }; guard let triggerDate = calculateReminderDate(for: event) else { return }; guard triggerDate > Date() else { return }; let content = buildNotificationContent(for: event); let request = UNNotificationRequest(identifier: notificationIdentifier(for: event), content: content, trigger: createTrigger(for: triggerDate)); center.add(request) { error in if let error { print("[NotificationManager] 调度事件提醒失败: \(error.localizedDescription)") } else { print("[NotificationManager] 已调度事件提醒: \(event.title) @ \(triggerDate)") } } }
    func scheduleReminder(for caseEvent: CaseEvent) { guard caseEvent.shouldRemind else { return }; let triggerDate = calculateReminderDate(for: caseEvent); guard triggerDate > Date() else { return }; let content = buildNotificationContent(for: caseEvent); let request = UNNotificationRequest(identifier: notificationIdentifier(for: caseEvent), content: content, trigger: createTrigger(for: triggerDate)); center.add(request) { error in if let error { print("[NotificationManager] 调度案件事件提醒失败: \(error.localizedDescription)") } else { print("[NotificationManager] 已调度案件事件提醒: \(caseEvent.title) @ \(triggerDate)") } } }
    func cancelReminder(for event: Event) { center.removePendingNotificationRequests(withIdentifiers: [notificationIdentifier(for: event)]); print("[NotificationManager] 已取消事件提醒: \(event.title)") }
    func cancelReminder(for caseEvent: CaseEvent) { center.removePendingNotificationRequests(withIdentifiers: [notificationIdentifier(for: caseEvent)]); print("[NotificationManager] 已取消案件事件提醒: \(caseEvent.title)") }
    func removeAllReminders(for event: Event) { cancelReminder(for: event) }
    func removeAllReminders(for caseEvent: CaseEvent) { cancelReminder(for: caseEvent) }
    private func calculateReminderDate(for event: Event) -> Date? { guard let eventDate = event.date else { return nil }; if let offset = event.reminderOffset { return eventDate.addingTimeInterval(-offset) }; if event.isAllDay { var components = Calendar.current.dateComponents([.year, .month, .day], from: eventDate); components.day! -= 1; components.hour = 21; components.minute = 0; return Calendar.current.date(from: components) }; return eventDate.addingTimeInterval(-15 * 60) }
    private func calculateReminderDate(for caseEvent: CaseEvent) -> Date { if let offset = caseEvent.reminderOffset { return caseEvent.date.addingTimeInterval(-offset) }; if caseEvent.isAllDay { var components = Calendar.current.dateComponents([.year, .month, .day], from: caseEvent.date); components.day! -= 1; components.hour = 21; components.minute = 0; return Calendar.current.date(from: components) ?? caseEvent.date }; return caseEvent.date.addingTimeInterval(-15 * 60) }
    private func buildNotificationContent(for event: Event) -> UNMutableNotificationContent { let content = UNMutableNotificationContent(); content.title = event.title; content.sound = .default; content.subtitle = "\(event.eventType.systemImageSymbol) \(event.eventType.rawValue)"; var bodyParts: [String] = []; if let date = event.date { bodyParts.append(dateDescription(for: date, isAllDay: event.isAllDay)) }; if let location = event.location, !location.isEmpty { bodyParts.append("📍 \(location)") }; if let summary = event.summary, !summary.isEmpty { bodyParts.append(summary) }; content.body = bodyParts.joined(separator: "
"); content.threadIdentifier = "event.\(event.id)"; content.categoryIdentifier = "EVENT_REMINDER"; return content }
    private func buildNotificationContent(for caseEvent: CaseEvent) -> UNMutableNotificationContent { let content = UNMutableNotificationContent(); content.title = caseEvent.title; content.sound = .default; if let caseName = caseEvent.case?.name { content.subtitle = "📋 \(caseName) · \(caseEvent.eventType.rawValue)" } else { content.subtitle = caseEvent.eventType.rawValue }; var bodyParts: [String] = []; bodyParts.append(dateDescription(for: caseEvent.date, isAllDay: caseEvent.isAllDay)); if let note = caseEvent.note, !note.isEmpty { bodyParts.append(note) }; content.body = bodyParts.joined(separator: "
"); content.threadIdentifier = "caseevent.\(caseEvent.id)"; content.categoryIdentifier = "CASE_EVENT_REMINDER"; return content }
    private func dateDescription(for date: Date, isAllDay: Bool) -> String { let f = DateFormatter(); f.locale = Locale(identifier: "zh_CN"); f.dateFormat = isAllDay ? "M月d日（EEE）全天" : "M月d日（EEE）HH:mm"; return f.string(from: date) }
    private func createTrigger(for date: Date) -> UNNotificationTrigger { let components = Calendar.current.dateComponents([.year, .month, .day, .hour, .minute], from: date); return UNCalendarNotificationTrigger(dateMatching: components, repeats: false) }
    private func notificationIdentifier(for event: Event) -> String { "event.reminder.\(event.id)" }
    private func notificationIdentifier(for caseEvent: CaseEvent) -> String { "caseevent.reminder.\(caseEvent.id)" }
}