import CoreSpotlight
import MobileCoreServices
import SwiftUI
import SwiftData
@MainActor final class SpotlightIndexManager { static let shared = SpotlightIndexManager(); private init() {}
    func indexPerson(_ person: Person) { let attributeSet = CSSearchableItemAttributeSet(contentType: .contact); attributeSet.displayName = person.name; attributeSet.nickname = person.name; attributeSet.organizationName = person.org; attributeSet.organizationDepartment = person.orgDepartment; attributeSet.jobTitle = person.title; var phoneNumbers: [String] = []; if let phone = person.phone { phoneNumbers.append(phone) }; if let phone2 = person.phone2 { phoneNumbers.append(phone2) }; if !phoneNumbers.isEmpty { attributeSet.phoneNumbers = phoneNumbers }; if let email = person.email { attributeSet.emailAddresses = [email] }; var keywords: [String] = [person.name]; if let org = person.org { keywords.append(org) }; keywords.append(contentsOf: person.roleTypes.map(\.rawValue)); attributeSet.keywords = keywords; attributeSet.contentDescription = "\(person.roleTypes.map(\.rawValue).joined(separator: "、"))" + (person.org.map { " · \($0)" } ?? ""); attributeSet.thumbnailData = roleColorThumbnail(for: person.roleTypes.first ?? .other); let item = CSSearchableItem(uniqueIdentifier: "person.\(person.id)", domainIdentifier: "com.youmind.islandlink.person", attributeSet: attributeSet); item.expirationDate = nil; CSSearchableIndex.default().indexSearchableItems([item]) { error in if let error { print("[SpotlightIndexManager] 索引联系人失败: \(error.localizedDescription)") } } }
    func indexCase(_ caseItem: Case) { let attributeSet = CSSearchableItemAttributeSet(contentType: .content); attributeSet.displayName = caseItem.name; attributeSet.title = caseItem.name; var subtitleParts: [String] = []; if let caseNumber = caseItem.caseNumber { subtitleParts.append(caseNumber) }; subtitleParts.append(caseItem.caseStatus.rawValue); attributeSet.contentDescription = subtitleParts.joined(separator: " · "); var keywords: [String] = [caseItem.name]; if let caseNumber = caseItem.caseNumber { keywords.append(caseNumber) }; if let court = caseItem.court { keywords.append(court) }; keywords.append(caseItem.caseType.rawValue); keywords.append(caseItem.caseStatus.rawValue); attributeSet.keywords = keywords; attributeSet.thumbnailData = statusColorThumbnail(for: caseItem.caseStatus); let item = CSSearchableItem(uniqueIdentifier: "case.\(caseItem.id)", domainIdentifier: "com.youmind.islandlink.case", attributeSet: attributeSet); item.expirationDate = nil; CSSearchableIndex.default().indexSearchableItems([item]) { error in if let error { print("[SpotlightIndexManager] 索引案件失败: \(error.localizedDescription)") } } }
    func indexEvent(_ event: Event) { let attributeSet = CSSearchableItemAttributeSet(contentType: .event); attributeSet.displayName = event.title; attributeSet.title = event.title; var descParts: [String] = [event.eventType.rawValue]; if let date = event.date { descParts.append(date.formatted(.dateTime.month(.abbreviated).day().hour().minute())) }; if let location = event.location, !location.isEmpty { descParts.append(location) }; attributeSet.contentDescription = descParts.joined(separator: " · "); var keywords: [String] = [event.title, event.eventType.rawValue]; if let location = event.location { keywords.append(location) }; if let summary = event.summary { keywords.append(summary) }; attributeSet.keywords = keywords; attributeSet.startDate = event.date; let item = CSSearchableItem(uniqueIdentifier: "event.\(event.id)", domainIdentifier: "com.youmind.islandlink.event", attributeSet: attributeSet); item.expirationDate = event.date?.addingTimeInterval(7 * 24 * 3600); CSSearchableIndex.default().indexSearchableItems([item]) { error in if let error { print("[SpotlightIndexManager] 索引事件失败: \(error.localizedDescription)") } } }
    func removePerson(_ person: Person) { CSSearchableIndex.default().deleteSearchableItems(withIdentifiers: ["person.\(person.id)"]) { error in if let error { print("[SpotlightIndexManager] 移除联系人索引失败: \(error.localizedDescription)") } } }
    func removeCase(_ caseItem: Case) { CSSearchableIndex.default().deleteSearchableItems(withIdentifiers: ["case.\(caseItem.id)"]) { error in if let error { print("[SpotlightIndexManager] 移除案件索引失败: \(error.localizedDescription)") } } }
    func removeEvent(_ event: Event) { CSSearchableIndex.default().deleteSearchableItems(withIdentifiers: ["event.\(event.id)"]) { error in if let error { print("[SpotlightIndexManager] 移除事件索引失败: \(error.localizedDescription)") } } }
    func rebuildAllIndices(modelContext: ModelContext) { let domains = ["com.youmind.islandlink.person", "com.youmind.islandlink.case", "com.youmind.islandlink.event"]; CSSearchableIndex.default().deleteSearchableItems(withDomainIdentifiers: domains) { error in if let error { print("[SpotlightIndexManager] 清空索引失败: \(error.localizedDescription)") } }; let personDescriptor = FetchDescriptor<person>(sortBy: [SortDescriptor(\.name)]); if let persons = try? modelContext.fetch(personDescriptor) { for person in persons { indexPerson(person) } }; let caseDescriptor = FetchDescriptor<case>(sortBy: [SortDescriptor(\.name)]); if let cases = try? modelContext.fetch(caseDescriptor) { for caseItem in cases { indexCase(caseItem) } }; let eventDescriptor = FetchDescriptor<event>(predicate: #Predicate { event in (event.statusRaw == "planned" || event.statusRaw == "confirmed") }, sortBy: [SortDescriptor(\.date)]); if let events = try? modelContext.fetch(eventDescriptor) { for event in events { indexEvent(event) } }; print("[SpotlightIndexManager] 全量 Spotlight 索引重建完成。") }
    private func roleColorThumbnail(for role: PersonRoleType) -> Data? { #if os(macOS); return nil; #else; let size = CGSize(width: 80, height: 80); let renderer = UIGraphicsImageRenderer(size: size); let image = renderer.image { ctx in let color: UIColor; switch role { case .judge: color = UIColor(red: 0.753, green: 0.224, blue: 0.169, alpha: 1); case .prosecutor: color = UIColor(red: 0.173, green: 0.435, blue: 0.675, alpha: 1); case .lawyer: color = UIColor(red: 0.239, green: 0.478, blue: 0.294, alpha: 1); case .party: color = UIColor(red: 0.831, green: 0.455, blue: 0.290, alpha: 1); case .police: color = UIColor(red: 0.357, green: 0.314, blue: 0.588, alpha: 1); case .witness: color = UIColor(red: 0.176, green: 0.498, blue: 0.459, alpha: 1); case .clerk: color = UIColor(red: 0.420, green: 0.314, blue: 0.275, alpha: 1); case .expert: color = UIColor(red: 0.659, green: 0.271, blue: 0.431, alpha: 1); case .other: color = UIColor(red: 0.380, green: 0.380, blue: 0.380, alpha: 1) }; ctx.cgContext.setFillColor(color.cgColor); ctx.cgContext.fillEllipse(in: CGRect(origin: .zero, size: size)) }; return image.pngData(); #endif }
    private func statusColorThumbnail(for status: CaseStatus) -> Data? { #if os(macOS); return nil; #else; let size = CGSize(width: 80, height: 80); let renderer = UIGraphicsImageRenderer(size: size); let image = renderer.image { ctx in let color: UIColor; switch status { case .consulting: color = UIColor(red: 0.086, green: 0.396, blue: 0.753, alpha: 1); case .retained: color = UIColor(red: 0.000, green: 0.537, blue: 0.482, alpha: 1); case .filing: color = UIColor(red: 0.086, green: 0.396, blue: 0.753, alpha: 1); case .inTrial: color = UIColor(red: 0.929, green: 0.424, blue: 0.008, alpha: 1); case .mediated: color = UIColor(red: 0.180, green: 0.490, blue: 0.196, alpha: 1); case .judged: color = UIColor(red: 0.180, green: 0.490, blue: 0.196, alpha: 1); case .enforcing: color = UIColor(red: 0.929, green: 0.424, blue: 0.008, alpha: 1); case .closed: color = UIColor(red: 0.565, green: 0.647, blue: 0.682, alpha: 1); case .appealed: color = UIColor(red: 0.878, green: 0.482, blue: 0.353, alpha: 1) }; ctx.cgContext.setFillColor(color.cgColor); ctx.cgContext.fillRoundedRect(CGRect(origin: .zero, size: size), cornerSize: CGSize(width: 16, height: 16)) }; return image.pngData(); #endif }
}
final class IslandLinkSpotlightHandler: CSIndexExtensionRequestHandler {
    override func searchableIndex(_ searchableIndex: CSSearchableIndex, reindexAllSearchableItemsWithAcknowledgementHandler acknowledgementHandler: @escaping () -> Void) { print("[IslandLinkSpotlightHandler] 系统请求重建 Spotlight 索引"); acknowledgementHandler() }
    override func searchableIndex(_ searchableIndex: CSSearchableIndex, reindexSearchableItemsWithIdentifiers identifiers: [String], acknowledgementHandler: @escaping () -> Void) { print("[IslandLinkSpotlightHandler] 系统请求重建部分索引：\(identifiers)"); acknowledgementHandler() }
}