import SwiftUI
import StoreKit
@MainActor final class SubscriptionManager: ObservableObject { static let shared = SubscriptionManager(); static let proAnnualID = "com.casenetwork.pro.annual"; static let freePersonLimit = 50; static let freeCaseEventLimit = 50
    enum ProSource { case purchased; case invitation }
    @Published var isPro: Bool = false; @Published var proSource: ProSource?; @Published var proProduct: Product?; @Published var isLoadingProducts = false; @Published var purchaseInProgress = false; @Published var purchaseError: String?; @Published var showUpgradeSheet = false; @Published var invitationExpiryDate: Date?; @Published var personCount: Int = 0; @Published var caseEventCount: Int = 0
    var invitationDaysRemaining: Int { guard let expiry = invitationExpiryDate else { return 0 }; return max(Calendar.current.dateComponents([.day], from: Date(), to: expiry).day ?? 0, 0) }
    var canAddPerson: Bool { isPro || personCount < Self.freePersonLimit }; var canAddCaseOrEvent: Bool { isPro || caseEventCount < Self.freeCaseEventLimit }
    var personLimitDisplay: String { isPro ? "无限" : "\(personCount)/\(Self.freePersonLimit)" }; var caseEventLimitDisplay: String { isPro ? "无限" : "\(caseEventCount)/\(Self.freeCaseEventLimit)" }
    var proPriceDisplay: String { proProduct?.displayPrice ?? "¥99.00" }; var proPeriodDisplay: String { if let p = proProduct?.subscription?.subscriptionPeriod { switch p.unit { case .year: return "年"; case .month: return "月"; case .week: return "周"; default: return "年" } }; return "年" }
    @AppStorage("subscription_isPro") private var storedPro = false; @AppStorage("invitation_expiry_timestamp") private var storedInvitationExpiry: Double = 0; private var updateListenerTask: Task<Void, Never>?
    private init() { isPro = storedPro; if isPro { proSource = .purchased }; let expiry = storedInvitationExpiry > 0 ? Date(timeIntervalSince1970: storedInvitationExpiry) : nil; if let expiry, expiry > Date() { isPro = true; proSource = .invitation; invitationExpiryDate = expiry } else if expiry != nil { storedInvitationExpiry = 0 }; loadProducts(); observeTransactions() }
    deinit { updateListenerTask?.cancel() }
    func loadProducts() { guard !isLoadingProducts else { return }; isLoadingProducts = true; Task { do { let products = try await Product.products(for: [Self.proAnnualID]); proProduct = products.first } catch { print("[SubscriptionManager] 加载产品失败: \(error.localizedDescription)") }; isLoadingProducts = false } }
    func purchase() async { guard let product = proProduct else { purchaseError = "订阅产品暂不可用"; return }; purchaseInProgress = true; purchaseError = nil; do { let result = try await product.purchase(); switch result { case .success(let verification): let transaction = try checkVerified(verification); await handlePurchaseSuccess(transaction); case .userCancelled: break; case .pending: purchaseError = "购买处理中，请稍候"; @unknown default: purchaseError = "未知的购买结果" } } catch { purchaseError = error.localizedDescription }; purchaseInProgress = false }
    func restorePurchases() async { purchaseInProgress = true; purchaseError = nil; do { for await result in StoreKit.Transaction.currentEntitlements { if case .verified(let transaction) = result, transaction.productID == Self.proAnnualID, transaction.revocationDate == nil, !(transaction.expirationDate.map { $0 < Date() } ?? false) { await handlePurchaseSuccess(transaction); break } } }; purchaseInProgress = false }
    func activateInvitation(until expiry: Date) { isPro = true; proSource = .invitation; invitationExpiryDate = expiry; storedInvitationExpiry = expiry.timeIntervalSince1970 }
    func deactivateInvitation() { if proSource == .invitation || !storedPro { isPro = storedPro; proSource = storedPro ? .purchased : nil }; invitationExpiryDate = nil; storedInvitationExpiry = 0 }
    private func handlePurchaseSuccess(_ transaction: StoreKit.Transaction) async { isPro = true; proSource = .purchased; storedPro = true; await transaction.finish() }
    private func observeTransactions() { updateListenerTask = Task.detached { for await result in StoreKit.Transaction.updates { guard case .verified(let transaction) = result else { continue }; await MainActor.run { if transaction.revocationDate != nil || (transaction.expirationDate.map { $0 < Date() } ?? false) { self.storedPro = false; if self.proSource != .invitation { self.isPro = false; self.proSource = nil } } else if transaction.productID == Self.proAnnualID { self.isPro = true; self.proSource = .purchased; self.storedPro = true } }; await transaction.finish() } } }
    private func checkVerified<T>(_ verification: VerificationResult<T>) throws -> T { switch verification { case .verified(let safe): return safe; case .unverified: throw VerificationError.unverified } }
    private enum VerificationError: Error { case unverified }
}