import SwiftUI
struct UpgradeSheet: View { @EnvironmentObject private var subManager: SubscriptionManager; @Environment(\.dismiss) private var dismiss
    var body: some View { NavigationStack { VStack(spacing: 0) { heroSection; featureList; Spacer(); purchaseSection }.background(Color.surfaceLight).toolbar { ToolbarItem(placement: .topBarTrailing) { Button { dismiss() } label: { Image(systemName: "xmark.circle.fill").font(.system(size: 24)).foregroundColor(.textTertiary) } } }.alert("购买失败", isPresented: .init(get: { subManager.purchaseError != nil }, set: { if !$0 { subManager.purchaseError = nil } })) { Button("知道了", role: .cancel) {} } message: { if let error = subManager.purchaseError { Text(error) } } } }
    private var heroSection: some View { VStack(spacing: Spacing.md) { ZStack { Circle().fill(LinearGradient(colors: [.tealLink.opacity(0.15), .oceanDeep.opacity(0.08)], startPoint: .topLeading, endPoint: .bottomTrailing)).frame(width: 80, height: 80); Image(systemName: "link.circle.fill").font(.system(size: 42)).foregroundStyle(LinearGradient(colors: [.tealLink, .oceanDeep], startPoint: .topLeading, endPoint: .bottomTrailing)) }; Text("连接 Pro").font(.cnTitle2).foregroundColor(.textPrimary); Text("解锁无限人脉与事项").font(.cnSubhead).foregroundColor(.textSecondary) }.padding(.top, Spacing.xxl).padding(.bottom, Spacing.lg) }
    private var featureList: some View { VStack(spacing: 0) { featureRow(icon: "person.2.fill", title: "无限人脉", description: "突破 \(SubscriptionManager.freePersonLimit) 人限制", color: .tealLink); Divider().padding(.leading, 52); featureRow(icon: "folder.fill", title: "无限案件与事件", description: "突破 \(SubscriptionManager.freeCaseEventLimit) 案件/事件限制", color: .oceanDeep); Divider().padding(.leading, 52); featureRow(icon: "icloud.fill", title: "iCloud 全设备同步", description: "iPhone、iPad、Mac 数据无缝衔接", color: .statusInfo); Divider().padding(.leading, 52); featureRow(icon: "lock.shield.fill", title: "优先新功能体验", description: "新功能上线第一时间解锁", color: .coralWarm) }.cardStyle().padding(.horizontal, Spacing.base) }
    private func featureRow(icon: String, title: String, description: String, color: Color) -> some View { HStack(spacing: Spacing.md) { Image(systemName: icon).font(.system(size: 20)).foregroundColor(color).frame(width: 28); VStack(alignment: .leading, spacing: 2) { Text(title).font(.cnBody).foregroundColor(.textPrimary); Text(description).font(.cnCaption1).foregroundColor(.textTertiary) }; Spacer(); Image(systemName: "checkmark").font(.system(size: 14, weight: .bold)).foregroundColor(.tealLink) }.padding(.horizontal, Spacing.base).padding(.vertical, 14) }
    private var purchaseSection: some View { VStack(spacing: Spacing.md) { HStack(alignment: .firstTextBaseline, spacing: Spacing.xs) { Text(subManager.proPriceDisplay).font(.cnTitle1).foregroundColor(.textPrimary); Text("/ \(subManager.proPeriodDisplay)").font(.cnCallout).foregroundColor(.textSecondary) }; Text("按年订阅，可随时取消").font(.cnCaption1).foregroundColor(.textTertiary); Button { Task { await subManager.purchase(); if subManager.isPro { dismiss() } } } label: { HStack { if subManager.purchaseInProgress { ProgressView().tint(.white) }; Text(subManager.purchaseInProgress ? "处理中…" : "订阅 Pro").font(.cnHeadline) }.frame(maxWidth: .infinity).padding(.vertical, 14).background(RoundedRectangle(cornerRadius: CornerRadius.button).fill(LinearGradient(colors: [.tealLink, .oceanDeep], startPoint: .leading, endPoint: .trailing))).foregroundColor(.white) }.disabled(subManager.purchaseInProgress); Button("恢复购买") { Task { await subManager.restorePurchases() } }.font(.cnFootnote).foregroundColor(.textTertiary).padding(.top, Spacing.xs); Text("购买确认后将从你的 Apple ID 账户扣款。
订阅将自动续订，除非在当前订阅期结束前至少 24 小时取消。").font(.cnCaption2).foregroundColor(.textTertiary).multilineTextAlignment(.center).padding(.top, Spacing.sm).padding(.horizontal, Spacing.base) }.padding(.vertical, Spacing.lg).padding(.horizontal, Spacing.base).background(.ultraThinMaterial) }
}
struct LimitReachedBanner: View { let type: LimitType; @EnvironmentObject private var subManager: SubscriptionManager
    enum LimitType { case person, caseOrEvent; var icon: String { switch self { case .person: return "person.2.fill"; case .caseOrEvent: return "folder.fill" } }; var label: String { switch self { case .person: return "人脉联系人"; case .caseOrEvent: return "案件与事件" } }; var limit: Int { switch self { case .person: return SubscriptionManager.freePersonLimit; case .caseOrEvent: return SubscriptionManager.freeCaseEventLimit } } }
    var body: some View { HStack(spacing: Spacing.md) { Image(systemName: type.icon).font(.system(size: 22)).foregroundColor(.coralWarm); VStack(alignment: .leading, spacing: 2) { Text("\(type.label)已达免费上限（\(type.limit) 个）").font(.cnCallout).foregroundColor(.textPrimary); Text("升级 Pro 即可无限制添加").font(.cnCaption1).foregroundColor(.textTertiary) }; Spacer(); Button { subManager.showUpgradeSheet = true } label: { Text("升级").font(.cnCaption2.weight(.bold)).foregroundColor(.white).padding(.horizontal, Spacing.md).padding(.vertical, Spacing.sm).background(RoundedRectangle(cornerRadius: CornerRadius.tag).fill(Color.tealLink)) } }.padding(Spacing.base).background(RoundedRectangle(cornerRadius: CornerRadius.card).fill(Color.surfaceCard).cardShadow()) }
}